# Generated by Django 6.0.7 on 2026-07-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='ends_date',
            new_name='end_date',
        ),
    ]
