# Generated by Django 6.0.7 on 2026-07-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attandance',
            new_name='Attendance',
        ),
    ]
