# Generated by Django 5.2.3 on 2026-08-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payroll_deductions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='pay_month',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.AddField(
            model_name='payroll',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_status',
            field=models.CharField(default='Paid', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
